### ISSUE TITLE
Not an issue, but a request.

### ISSUE THREAD

**Issue by takerisksbro** [cash/minesweeper#2]
I'm sorry to contact you about this and I know that it's not an issue. But I am a young student from London who wishes to build a career using developer skills. Your username @ks has been has been my dream username for a long while. It would allow me to give my username to friends more easily and it's short and easy to remember.

I apologise again for contacting you about this.
Much love, ❤️

**Comment by J4M13four20** [comment]
Cash @takerisksbro
